# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b17dfa131a2e2cc6b4ff58810b33140fdc8852aa9cd8e935ad799f4329e6bb2d4cb0e48590de46e9293471d9644a8fa8bc677dfc76792765b7f2955cbc18529

test:
  secret_key_base: a65ce4a81318475ee02edd94708ca4cd3d65839d36207b5ab6fda25963277a81f737d344baa097351b7e33f04fa84b139bd4f185ab400a3f6c068cccfe3e2e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
